# Generated by Django 2.1.4 on 2023-03-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_bet', models.CharField(max_length=12)),
                ('timestamp', models.IntegerField()),
                ('bet_status', models.CharField(max_length=25)),
                ('bet_color', models.IntegerField()),
                ('bet_roll', models.IntegerField()),
            ],
        ),
    ]
