# Generated by Django 2.1.4 on 2023-03-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230310_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverresult',
            name='total_bank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serverresult',
            name='total_bets_placed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serverresult',
            name='total_black_bets_placed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serverresult',
            name='total_black_eur_bet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serverresult',
            name='total_eur_bet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serverresult',
            name='total_red_bets_placed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serverresult',
            name='total_red_eur_bet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serverresult',
            name='total_white_bets_placed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serverresult',
            name='total_white_eur_bet',
            field=models.IntegerField(null=True),
        ),
    ]
