# Generated by Django 2.1.4 on 2023-03-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230310_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverresult',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
