# Generated by Django 2.1.4 on 2023-03-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230310_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverresult',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
