# Generated by Django 2.1.4 on 2023-03-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230310_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverresult',
            name='total_bets_placed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='serverresult',
            name='total_black_bets_placed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='serverresult',
            name='total_black_eur_bet',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='serverresult',
            name='total_eur_bet',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='serverresult',
            name='total_red_bets_placed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='serverresult',
            name='total_red_eur_bet',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='serverresult',
            name='total_retention_eur',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='serverresult',
            name='total_white_bets_placed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='serverresult',
            name='total_white_eur_bet',
            field=models.FloatField(null=True),
        ),
    ]
