# Generated by Django 2.1.4 on 2023-03-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230310_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlBetResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_bet', models.CharField(max_length=12)),
                ('timestamp', models.FloatField()),
                ('first_id_gale', models.CharField(max_length=12)),
                ('color', models.IntegerField()),
                ('source', models.CharField(max_length=35)),
                ('amount', models.FloatField()),
                ('score_bet', models.FloatField()),
                ('amount_return', models.FloatField()),
                ('gale', models.IntegerField()),
                ('status_bet', models.CharField(max_length=16)),
                ('win', models.IntegerField()),
                ('win_status', models.IntegerField()),
                ('result_color', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='serverresult',
            name='bet_color',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serverresult',
            name='bet_roll',
            field=models.IntegerField(),
        ),
    ]
