# Generated by Django 2.1.4 on 2023-03-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230314_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlbetresult',
            name='status_bet',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
