# Generated by Django 2.1.4 on 2023-03-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230314_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_bet', models.CharField(max_length=12)),
                ('timestamp', models.FloatField()),
                ('color', models.IntegerField()),
                ('amount', models.FloatField()),
                ('currency_type', models.CharField(max_length=3)),
                ('user', models.CharField(max_length=12)),
            ],
        ),
    ]
