# Generated by Django 4.1.7 on 2023-04-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_controlbetresult_result_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoControlBetResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_bet', models.CharField(max_length=12)),
                ('timestamp', models.FloatField()),
                ('timestamp_signal', models.FloatField()),
                ('color', models.IntegerField()),
                ('source', models.CharField(max_length=35)),
                ('win', models.BooleanField()),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('gale', models.IntegerField()),
                ('amount', models.FloatField()),
                ('balanceWin', models.FloatField()),
            ],
        ),
    ]
