# Generated by Django 4.1.7 on 2023-05-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_gocontrolbetresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoUserResults',
            fields=[
                ('ID_bet', models.CharField(max_length=12)),
                ('ID_bet_uniqa', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('timestamp', models.FloatField()),
                ('color', models.IntegerField()),
                ('amount', models.FloatField()),
                ('currency_type', models.CharField(max_length=3)),
                ('user', models.CharField(max_length=12)),
            ],
        ),
    ]
